version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'kplatform'
      MYSQL_USER: 'kadmin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'krootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3307:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - kplatfrom-db:/var/lib/mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  kplatfrom-db: